apiVersion: v1
kind: Pod
metadata:
  name: baoxiang
  namespace: chrs
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "10Gi"
      requests:
        memory: "10Gi"
    volumeMounts:
    - mountPath: /volume
      name: volume
  restartPolicy: Never
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: volume
  
