apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  namespace: chrs
spec:
  containers:
  - name: vol-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /volume
      name: volume
  restartPolicy: Never
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: volume
