kind: PersistentVolume
apiVersion: v1
metadata:
  name: baoxiang-volume
  namespace: chrs
  labels:
  type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jovyan/Mathematica"
