kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: baoxiang
  namespace: chrs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
