kind: PersistentVolume
apiVersion: v1
metadata:
  name: baoxiang
  namespace: chrs
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

